config/routes.rb
Rails.application.routes.draw do
    
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
root "homes#top"
get "home/about" => "homes#about"
resources :books
resources :users
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  
   self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  validates :title, presence:true
  validates :body, presence:true,length:{ minimum: 1, maximum: 200 }
end

app/models/post_image.rb
class PostImage < ApplicationRecord
   has_one_attached :image
   belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :profile_image

  has_many :books, dependent: :destroy

  def get_profile_image(width,height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
  validates :name,uniqueness: true,
  length: { minimum: 2, maximum: 20 }
  
   validates :introduction,length: { maximum: 50 }
end
 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
before_action :configure_permitted_parameters, if: :devise_controller?
before_action :authenticate_user!, except: [:top,:about]

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end


 private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :correct_user, only: [:edit, :update]

  def new
  end

  def index
    @book =Book.new
    @books = Book.all
    @user = current_user
  end
  def create
    @book = Book.new(books_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
    redirect_to book_path(@book.id)
    else
    @books = Book.all
    @user = current_user
    render :index
    end
  end

  def show
    @new_book= Book.new
    @books = Book.all
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def edit
      @book = Book.find(params[:id])
  end

  def update
    @book=Book.find(params[:id])
    if @book.update(books_params)
      flash[:notice]="You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end


  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to "/books"
  end

  private

  def books_params
    params.require(:book).permit(:title, :body)
  end
  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(books_path) unless @user == current_user
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/post_image_controller.rb
class PostImageController < ApplicationController
  def new
    @post_image = post_image.new
  end

  def index
  end
  
  def create
    @post_image = PostImage.new(post_image_params)
    @post_image.user_id = current_user.id
    @post_image.save
    redirect_to post_images_path
  end

  def show
  end
  
   def destroy
   end
  
   private

  def post_image_params
    params.require(:post_image).permit( :image, :name, :introduction)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @book =Book.new
    @book = Book.all
    @users = User.all
    @user = current_user
  end
  def create
    @book = Book.new(books_params)
    @book.user_id = current_user.id
    @book.save
    flash[:notice] = "You have updated user successfully."
    redirect_to books_path(@book.id)
  end

  def show
    @book = Book.all
    @users = User.all
    @user = User.find(params[:id])
    @books = @user.books

  end
 def edit
  @user = User.find(params[:id])
  if(@user != current_user)
  redirect_to user_path(current_user.id)
  end
 end

def update
  is_matching_login_user
  @user = User.find(params[:id])
  if @user.update(user_params)
    flash[:notice] = "You have updated user successfully."
  redirect_to user_path(@user.id)
  else
    flash[:notice] = " errors prohibited this obj from being saved:"
    render :edit
  end
end

private

  def user_params
    params.require(:user).permit(:name,:introduction,:profile_image)
  end

  def is_matching_login_user
    user_id = params[:id].to_i
    unless user_id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_image_helper.rb
module PostImageHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
  <div class="col-md-3" >
        <h2>Users info</h2>
          <tb><%= image_tag @user.get_profile_image(100,100), size: "100x100" %></tb>

             <table class='table table-hover table-inverse'>
               <tr>
                 <th>name</th><th><%=@user.name %></th>
                </tr>
                   <tr>
                       <th>introduction</th><th><%= @user.introduction%></th>
                    </tr>
             </table>
                        <div class="row">
                         <%= link_to edit_user_path(@user), class: "btn btn-light btn-outline-secondary btn-block" do %>
                            <i class="fas fa-user-cog"></i>

                               <% end %>
                        </div>


                               <h2>New book</h2>
                               <div class="md-3">
                                   <%= form_with model: Book.new do |f| %>

                                  <h5>Title</h5>
                                    <%= f.text_field :title, class:"col-xs-12"%>
                                   <h5>Body</h5>
                                      <%= f.text_area :body, class:"col-xs-12" %>
                                          <br><%= f.submit "Create Book", class: "col-xs-12 btn btn-success" %></br>
                                </div>
                                   <% end %>


                </div>

app/views/books/edit.html.erb
<div class="box">
   
  <%= flash[:notice] %>
</div>
 <% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
  <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
      <% end %>

    </ul>

   <% end %>
  
 <div class="container">  
  <div classs="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
<h1>Editing Book</h1>


<%= form_with model: @book do |f| %>

<h4>title</h4>
<%= f.text_field :title %>

<h4>Opinion</h4>
<%= f.text_area :body %><br>

<%= f.submit 'Update Book', class: " btn btn-secondary" %>

<% end %>
<%= link_to "Show", book_path(@book.id) %>
 |
<%= link_to "Back", books_path %>
   </div>
  </div>
  </div>
</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <% end %>
  <ul>
  <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
      <% end %>

<div class="container px-5 px-sm-0">
     <div class="row">
        <%= render 'books/list',books: @books %>

    <div class= "col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class='table table-hover table-inverse'>

      <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th><colspan="3"></th>
      </tr>
      <% @books.each do |book| %>
      <tr>
      <td>
      <%= link_to user_path(book.user.id) do %>
      <%= image_tag book.user.get_profile_image(100,100), size: "100x100" %></br>
       <% end %> 
       </td>
      <td><%=link_to book.title, book_path(book.id)%></td>
      <td><%= book.body %></td>
      </tr>
      <% end %>
      </table>
            </div>
           </div>
          </div>
        </div>

app/views/books/new.html.erb
<h1>New Book</h1>
<%= form_with model: Book.new do |f| %>
<h2>title</h2>
<%= f.text_field :title %>

<h2>body</h2>
<%= f.text_area :body %>

 <%= f.submit 'Create Book' %>

<% end %>

app/views/books/show.html.erb
<div>
  <%= flash[:notice] %>
</div>
  <div class="container">
     <div class="row">
        <%= render 'list',books: @books %>
       <div class= "col-md-8 offset-md-1">
    
       <h2>Book detail</h2>
      <table class='table table-hover table-inverse'>

      <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
      </tr>

     
      <tr>
      <td>
      <%= image_tag @book.user.get_profile_image(100,100), size: "100x100" %></br>
      <%= link_to @book.user.name, user_path(@user.id) %></td>
      <td><%=link_to @book.title, book_path(@book.id)%></td>
      <td><%= @book.body %></td>
      <% if @user == current_user %>
      <td><%= link_to"Edit","/books/#{@book.id}/edit", class:"btn btn-success"%></td>
      <td><%= link_to"Destroy","/books/#{@book.id}",method: :delete,"data-confirm"=>"Are you sure?",class:"btn btn-danger" %>
      <% end %>
      </tr>
      
      </table>
               </div>
            </div>
       </div>

app/views/homes/about.html.erb
<script src="https://kit.fontawesome.com/5426e91a66.js" crossorigin="anonymous"></script>


<h1 class="text-center">Welcome to <i class="fas fa-book"></i>Bookers!</h1>

app/views/homes/top.html.erb
<script src="https://kit.fontawesome.com/5426e91a66.js" crossorigin="anonymous"></script>
<div class="box">

<head>
    <title>Bookers2</title>
</head>




<div class='body'>
 <div class='container'>
   <div class="row">
  <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
<div>
  <%= flash[:notice] %>
</div>
<div class="container">
  <div calss="row">
<h1>welcome to<i class="fas fa-book"></i>Bookers!!</h1>

<p>In<i class="fas fa-book"></i><strong>Bookers</strong>,</p>
<p>you can share and exchange your opinions , inpressions , and emotions</p>
<p>about varioius books!</p>
</div>

  <div class="btn-wrapper col-10 mx-auto">
      <div class="row">
      <div>

      <div class="row">
      <p><a class="btn btn-info btn-sm btn-block mb-3 " href="/users/sign_in">Log in</a></p></br>
    </div>
      <div class="row">
      <p><a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a></p>
      </div>
     </div>
   </div>
  </div>
 </div>

  </body>


  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <script src="https://kit.fontawesome.com/5426e91a66.js" crossorigin="anonymous"></script>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
       <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
         <ul class="list-unstyled">
        <div class="container">
          <a class="navbar-brand" href="/">
            <span>Bookers</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="true" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">

    <% if user_signed_in? %>

        <li class="nav-link text-light">
        <%= link_to user_path(current_user.id) do %>
        <i class="fas fa-home"></i> Home
        <% end %>
        </li>
        <li class="nav-link text-light">
        <%= link_to users_path do %>
        <i class="fas fa-users"></i> Users
        <% end %>
        </li>
        <li class="nav-link text-light">
         <%= link_to books_path do %>
        <i class="fas fa-book-open"></i></i> Books
        <% end %>
        </li>
      <li class="nav-link text-light">
        <%= link_to destroy_user_session_path, method: :delete do %>
        <i class="fas fa-sign-out-alt"></i>Log out
        <% end %>
        </li>


    <% else %>
      <li class="nav-item">
        <%= link_to root_path do %>
        <i class="fas fa-home"></i> Home
        <% end %>
      </li>
       <li class="nav-item">
        <%= link_to home_about_path do %>
        <i class="fas fa-link"></i> About
        <% end %>
      </li>
       <li class="nav-item">
        <%= link_to new_user_registration_path do %>
        <i class="fas fa-user-plus"></i> Sign up
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to  new_user_session_path do %>
        <i class="fas fa-sign-in-alt"></i> Log in
         <% end %>

          </div>
        </div>
        </ul>
      </nav>
      <% end %>
    </header>

    <%= yield %>
     <footer class="footer"r>
     <p class="text-center ">CopyRight Infratop.inc</p>
    </footer>

  </body>
</html>

app/views/post_image/index.html.erb
<h1>PostImage#index</h1>
<p>Find me in app/views/post_image/index.html.erb</p>

app/views/post_image/show.html.erb
<h1>PostImage#show</h1>
<p>Find me in app/views/post_image/show.html.erb</p>

app/views/users/edit.html.erb
 <% if @user.errors.any? %>
  <%= @user.errors.count %>errors prohibited this book from being saved:
  <% end %>
  <ul>
  <% @user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
      <% end %>

<div class="container">
  <div class="col-sm-12bcol-md-8 col-lg-5px-5 px-sm-0 mx-auto">
<h2>User   info</h2>

<%= form_with model: @user do |f| %>
    <h4>Name</h4>
    <%= f.text_field :name %>
    <h4>Image</h4>
  <%= f.file_field :profile_image %>
    <h4>introduction</h4>
      <%= f.text_area :introduction %></br>
    <%= f.submit 'Update User',class: "btn btn-secondary" %>
<% end %>
 </div>
</div>

app/views/users/index.html.erb
 <div>
  <%= flash[:notice] %>
</div>
<div class="container px-5 px-sm-0">
     <div class="row">
        <%= render 'books/list',books: @books %>

      <div class= "col-md-8 offset-md-1">
      <h2>Users</h2>

      <table class='table'>
      <thead>
      <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
      </tr>
      </thead>
      <tbody>
      <% @users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image(100,100), size: "100x100" %></td>
         <td><%= user.name %></td>
            <td><%=link_to "Show", user_path(user.id)%></td>

        </tr>
         <% end %>
               </tbody>
              </table>
              </div>
          </div>
       </div>

app/views/users/show.html.erb
 <div>
  <%= flash[:notice] %>
</div>
<div class="container px- px-sm-0">
     <div class="row">
        <%= render 'books/list',books: @books %>
        <div class= "col-md-8 offset-md-1">
          <h2>Book detail</h2>
            <table class='table table-hover table-inverse'>

               <tr>
                  <th></th>
                   <th>Title</th>
                     <th>Opinion</th>
                        <th colspan="3"></th>
                           </tr>
                             <% @books.each do |book| %>
                                 <tr>
                                  <td>
                                     <%= link_to user_path(book.user.id) do %>
                                       <%= image_tag book.user.get_profile_image(100,100), size: "100x100" %></br>
                                          <% end %>
  
                                      <td><%=link_to book.title, book_path(book.id)%></td>
                                           <td><%= book.body %></td>
                                             </tr>
                               <% end %>
                 </table>
        </div>
      </div>
    </div>